/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:46685'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:38840'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:36500'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:38203'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:35937'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:33441'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:39632'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:39367'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:46050'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:32877'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:46630'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:35890'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:46261'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:39556'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:36047'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:43825'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:46454'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:43428'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:33095'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:33191'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:36997'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:35158'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:41347'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:46080'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:38915'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:38354'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:46387'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.132:33352'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:42677
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:42677
distributed.worker - INFO -              nanny at:         172.30.8.132:46387
distributed.worker - INFO -              bokeh at:         172.30.8.132:46504
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-h46qbot_
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:39355
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:39355
distributed.worker - INFO -              nanny at:         172.30.8.132:38915
distributed.worker - INFO -              bokeh at:         172.30.8.132:34795
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-euttk_m7
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:45775
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:45775
distributed.worker - INFO -              nanny at:         172.30.8.132:39556
distributed.worker - INFO -              bokeh at:         172.30.8.132:42383
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0xnfvs03
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:38422
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:38422
distributed.worker - INFO -              nanny at:         172.30.8.132:46050
distributed.worker - INFO -              bokeh at:         172.30.8.132:34168
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-e7cozk6w
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:39532
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:39532
distributed.worker - INFO -              nanny at:         172.30.8.132:33441
distributed.worker - INFO -              bokeh at:         172.30.8.132:35329
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kq3ccjw5
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:38767
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:38767
distributed.worker - INFO -              nanny at:         172.30.8.132:43428
distributed.worker - INFO -              bokeh at:         172.30.8.132:40359
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zvj0ypmf
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:33087
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:33087
distributed.worker - INFO -              nanny at:         172.30.8.132:38840
distributed.worker - INFO -              bokeh at:         172.30.8.132:35577
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1tbbixv1
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:40467
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:40467
distributed.worker - INFO -              nanny at:         172.30.8.132:46685
distributed.worker - INFO -              bokeh at:         172.30.8.132:37002
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-roziveh0
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:35917
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:35917
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -              nanny at:         172.30.8.132:46261
distributed.worker - INFO -              bokeh at:         172.30.8.132:42840
distributed.core - INFO - Starting established connection
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-l8scmzx8
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:34383
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:34383
distributed.worker - INFO -              nanny at:         172.30.8.132:36500
distributed.worker - INFO -              bokeh at:         172.30.8.132:40332
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-getdm281
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:45359
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:45359
distributed.worker - INFO -              nanny at:         172.30.8.132:39632
distributed.worker - INFO -              bokeh at:         172.30.8.132:34870
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-nkgkwy3u
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:38619
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:38619
distributed.worker - INFO -              nanny at:         172.30.8.132:46080
distributed.worker - INFO -              bokeh at:         172.30.8.132:38495
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-imr3mdh4
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:34207
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:34207
distributed.worker - INFO -              nanny at:         172.30.8.132:38354
distributed.worker - INFO -              bokeh at:         172.30.8.132:46774
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-er_1lu7x
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:39616
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:39616
distributed.worker - INFO -              nanny at:         172.30.8.132:39367
distributed.worker - INFO -              bokeh at:         172.30.8.132:42601
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:44816
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:44816
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         172.30.8.132:41347
distributed.worker - INFO -              bokeh at:         172.30.8.132:32844
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-afbfngi3
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-nq5mjffk
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:34177
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:34177
distributed.worker - INFO -              nanny at:         172.30.8.132:36047
distributed.worker - INFO -              bokeh at:         172.30.8.132:38875
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-g3o51_j2
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:42086
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:42086
distributed.worker - INFO -              nanny at:         172.30.8.132:46454
distributed.worker - INFO -              bokeh at:         172.30.8.132:39684
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-i20lz0jq
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:34806
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:34806
distributed.worker - INFO -              nanny at:         172.30.8.132:36997
distributed.worker - INFO -              bokeh at:         172.30.8.132:41856
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-6fmtbi32
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:46666
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:46666
distributed.worker - INFO -              nanny at:         172.30.8.132:43825
distributed.worker - INFO -              bokeh at:         172.30.8.132:43942
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-oocas4tg
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:36164
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:36164
distributed.worker - INFO -              nanny at:         172.30.8.132:35158
distributed.worker - INFO -              bokeh at:         172.30.8.132:38063
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-sn6k7c9s
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:38512
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:38512
distributed.worker - INFO -              nanny at:         172.30.8.132:33095
distributed.worker - INFO -              bokeh at:         172.30.8.132:42764
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-wyito1w4
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:39781
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:39781
distributed.worker - INFO -              nanny at:         172.30.8.132:46630
distributed.worker - INFO -              bokeh at:         172.30.8.132:39364
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ek645rz6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:45635
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:45635
distributed.worker - INFO -              nanny at:         172.30.8.132:32877
distributed.worker - INFO -              bokeh at:         172.30.8.132:41182
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ga_k8fn1
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:40712
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:40712
distributed.worker - INFO -              nanny at:         172.30.8.132:35937
distributed.worker - INFO -              bokeh at:         172.30.8.132:38278
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-4lsfybd3
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:32953
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:32953
distributed.worker - INFO -              nanny at:         172.30.8.132:38203
distributed.worker - INFO -              bokeh at:         172.30.8.132:42592
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-v40nk7em
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:38454
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:38454
distributed.worker - INFO -              nanny at:         172.30.8.132:33352
distributed.worker - INFO -              bokeh at:         172.30.8.132:46642
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-t7ny5532
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:37789
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:37789
distributed.worker - INFO -              nanny at:         172.30.8.132:35890
distributed.worker - INFO -              bokeh at:         172.30.8.132:40809
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-elx9_fwm
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.132:33164
distributed.worker - INFO -          Listening to:   tcp://172.30.8.132:33164
distributed.worker - INFO -              nanny at:         172.30.8.132:33191
distributed.worker - INFO -              bokeh at:         172.30.8.132:38372
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-8riatkpe
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Event loop was unresponsive in Worker for 163.33s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 163.33s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f4568a60>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[ 0.12523656,  0.13468957,  0.14250718, ..., -0.02036797,
          -0.01917956, -0.01753058],
         [ 0.12918535,  0.13754638,  0.14406866, ..., -0.01733485,
          -0.01630662, -0.01412086],
         [ 0.13205884,  0.13799393,  0.14074562, ..., -0.01419148,
          -0.0137383 , -0.01136499],
         ...,
         [ 0.06821305,  0.06110623,  0.05403066, ..., -0.1357057 ,
          -0.13807507, -0.1394015 ],
         [ 0.07898553,  0.07413857,  0.06830866, ..., -0.13827308,
          -0.13994046, -0.14077008],
         [ 0.08748724,  0.08514481,  0.08146962, ..., -0.14144057,
          -0.14272754, -0.14324139]]]], dtype=float32), array([[[[-0.01648217, -0.0160342 , -0.01534883, ..., -0.05914621,
          -0.06138703, -0.06369181],
         [-0.01229947, -0.01155902, -0.01023163, ..., -0.05932731,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f41cee18>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[ 0.04087652,  0.04131968,  0.04128677, ..., -0.06411117,
          -0.0715801 , -0.07967937],
         [ 0.03659294,  0.03613569,  0.03545766, ..., -0.07031562,
          -0.0785483 , -0.08677141],
         [ 0.03180206,  0.03059016,  0.02957259, ..., -0.07704709,
          -0.08592456, -0.09419318],
         ...,
         [-0.1866735 , -0.1977285 , -0.2089647 , ..., -0.36235276,
          -0.36320055, -0.3642947 ],
         [-0.19221686, -0.20278725, -0.21350814, ..., -0.36673495,
          -0.36769393, -0.36830324],
         [-0.19747674, -0.20756385, -0.21777923, ..., -0.3709847 ,
          -0.37167922, -0.37134612]]]], dtype=float32), array([[[[-0.08774431, -0.09654688, -0.10661859, ..., -0.07093135,
          -0.08317266, -0.09366395],
         [-0.09480403, -0.10364819, -0.11349571, ..., -0.06100656,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f45c10d0>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[0.12477154, 0.12412829, 0.12345503, ..., 0.01236286,
          0.01056479, 0.00804053],
         [0.12420169, 0.12353083, 0.12277746, ..., 0.01288789,
          0.01113015, 0.00869757],
         [0.12337703, 0.12249016, 0.1215192 , ..., 0.01346917,
          0.01176053, 0.00942659],
         ...,
         [0.08574641, 0.08516693, 0.08458113, ..., 0.0364891 ,
          0.03616906, 0.03624925],
         [0.08296137, 0.08244193, 0.08192796, ..., 0.03593815,
          0.03558158, 0.035625  ],
         [0.0801165 , 0.07968505, 0.07927571, ..., 0.03507226,
          0.03474435, 0.03480994]]]], dtype=float32), array([[[[ 0.00467099,  0.00071007, -0.00342309, ...,  0.2572025 ,
           0.25511643,  0.2524121 ],
         [ 0.00544604,  0.0015995 , -0.00248991, ...,  0.2711833 ,
           0.26903266,  0.26621175],
         [ 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f454a158>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[-0.01906601, -0.02076061, -0.02253597, ..., -0.1838661 ,
          -0.17986877, -0.17312746],
         [-0.02171547, -0.02326267, -0.02486173, ..., -0.17915456,
          -0.17529725, -0.1683663 ],
         [-0.02439574, -0.02582321, -0.02728167, ..., -0.17438518,
          -0.17066124, -0.16355745],
         ...,
         [-0.07614721, -0.07685702, -0.07737064, ..., -0.03519274,
          -0.03127708, -0.02698758],
         [-0.07556355, -0.07623108, -0.07675583, ..., -0.03243475,
          -0.02868685, -0.02457326],
         [-0.07460608, -0.07520904, -0.07572994, ..., -0.02924566,
          -0.02562252, -0.02172973]]]], dtype=float32), array([[[[-0.16344468, -0.15303971, -0.14556205, ..., -0.26499674,
          -0.26262724, -0.25918922],
         [-0.15845257, -0.1480131 , -0.14065596, ..., -0.27143312,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f4528d08>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32), array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32), array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32)], [array([[[[ 0.       
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f41cae18>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[-0.09679641, -0.09947817, -0.10181464, ..., -0.03254109,
          -0.03074311, -0.02978405],
         [-0.09535739, -0.09775476, -0.09973098, ..., -0.02917227,
          -0.0272607 , -0.02632535],
         [-0.09350383, -0.09545945, -0.09704179, ..., -0.02590866,
          -0.02386986, -0.02294104],
         ...,
         [-0.05637401, -0.05212881, -0.04784278, ...,  0.00197433,
           0.0128961 ,  0.02249876],
         [-0.05623837, -0.05183193, -0.04743571, ...,  0.00312793,
           0.01366607,  0.02289513],
         [-0.05627145, -0.05169898, -0.04719734, ...,  0.00443947,
           0.01459181,  0.02339303]]]], dtype=float32), array([[[[-0.02857992, -0.02679189, -0.02458994, ..., -0.00597145,
           0.00263779,  0.01115468],
         [-0.0251991 , -0.02344321, -0.02118898, ..., -0.01007641,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f4262730>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]]), array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]]]])], [array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ...
kwargs:    {}
Exception: OSError("Timed out trying to connect to 'tcp://172.30.100.1:40264' after 3 s: connect() didn't finish in time")

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f44c3268>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[-0.05839588, -0.05697589, -0.05521921, ...,  0.02931345,
           0.02645001,  0.02266398],
         [-0.05731237, -0.0558145 , -0.0539974 , ...,  0.02838683,
           0.02298834,  0.01754079],
         [-0.05621903, -0.05465933, -0.0527962 , ...,  0.02144872,
           0.01452562,  0.00863785],
         ...,
         [-0.0226684 , -0.0213268 , -0.02094186, ...,  0.00674903,
           0.00746347,  0.00800389],
         [-0.04980188, -0.04858936, -0.04735574, ..., -0.01280214,
          -0.01258645, -0.01237504],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ]]]], dtype=float32), array([[[[ 0.01856554,  0.01469318,  0.01130152, ...,  0.        ,
           0.        ,  0.        ],
         [ 0.01267801,  0.00856878,  0.005292  , ...,  0.        ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f44b2bf8>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[0.14687988, 0.14515226, 0.14316647, ..., 0.05652366,
          0.05457103, 0.05181031],
         [0.14564392, 0.14356339, 0.14095493, ..., 0.05703828,
          0.05518079, 0.05254831],
         [0.1442249 , 0.1415497 , 0.13825317, ..., 0.05760185,
          0.05585528, 0.0533722 ],
         ...,
         [0.09643116, 0.0963997 , 0.09619664, ..., 0.07836899,
          0.07869512, 0.07926001],
         [0.09331145, 0.09341177, 0.09333718, ..., 0.07799844,
          0.07823211, 0.07875486],
         [0.09010143, 0.09035673, 0.09044265, ..., 0.07733041,
          0.07751254, 0.07803249]]]], dtype=float32), array([[[[ 0.04852702,  0.04503627,  0.04161322, ...,  0.24726279,
           0.24824324,  0.24817212],
         [ 0.04935891,  0.0459145 ,  0.04252022, ...,  0.23627621,
           0.2395089 ,  0.24211952],
         [ 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f4299e18>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[-0.11509279, -0.11614034, -0.11686641, ..., -0.07671208,
          -0.07828131, -0.07523088],
         [-0.11638714, -0.11718623, -0.11766708, ..., -0.07058775,
          -0.07413974, -0.07272726],
         [-0.11829928, -0.11885388, -0.11908256, ..., -0.06370509,
          -0.06901114, -0.0695401 ],
         ...,
         [-0.19889398, -0.21220908, -0.22089274, ...,  0.06633944,
           0.09254616,  0.11584674],
         [-0.19369557, -0.20750795, -0.21719316, ...,  0.04390937,
           0.07006276,  0.0988571 ],
         [-0.18851496, -0.20276779, -0.21335207, ...,  0.02818925,
           0.04977144,  0.07718699]]]], dtype=float32), array([[[[-0.07009149, -0.06610156, -0.06404069, ...,  0.03599297,
           0.03680406,  0.038357  ],
         [-0.06792099, -0.06333712, -0.06079284, ...,  0.03725988,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f44ed510>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[-0.06573746, -0.05291406, -0.03856204, ...,  0.46393836,
           0.4691881 ,  0.47547337],
         [-0.06650536, -0.05382912, -0.04002076, ...,  0.46649238,
           0.47184625,  0.47904056],
         [-0.06680661, -0.05412043, -0.04067212, ...,  0.46849087,
           0.4741526 ,  0.48244837],
         ...,
         [ 0.12990066,  0.14336231,  0.15602507, ...,  0.451828  ,
           0.4470338 ,  0.4406324 ],
         [ 0.1381669 ,  0.1517912 ,  0.16466308, ...,  0.44241092,
           0.43654037,  0.4288236 ],
         [ 0.14675082,  0.16052844,  0.17353976, ...,  0.43192157,
           0.42487824,  0.4158331 ]]]], dtype=float32), array([[[[ 0.4879229 ,  0.506617  ,  0.5290498 , ..., -0.12983716,
          -0.1396738 , -0.13538434],
         [ 0.49265388,  0.51189333,  0.53399736, ..., -0.12932286,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f41afea0>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[-0.11656926, -0.10667501, -0.09773199, ...,  0.3321181 ,
           0.33347213,  0.33448225],
         [-0.1222879 , -0.11360724, -0.10329309, ...,  0.3320644 ,
           0.33337015,  0.33426756],
         [-0.12500136, -0.1190296 , -0.10899611, ...,  0.3318456 ,
           0.3332605 ,  0.33416605],
         ...,
         [-0.03144158, -0.02376721, -0.01326895, ...,  0.39755148,
           0.39783502,  0.395772  ],
         [-0.02290245, -0.01428085, -0.00293315, ...,  0.40159824,
           0.4004301 ,  0.3968964 ],
         [-0.01361371, -0.00411013,  0.0080107 , ...,  0.40478867,
           0.40208814,  0.39708462]]]], dtype=float32), array([[[[0.3354277 , 0.33644387, 0.33748865, ..., 0.2686129 ,
          0.27537292, 0.2760125 ],
         [0.3350495 , 0.33590183, 0.33684704, ..., 0.2804457 ,
          0.2772135 , 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f4142268>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[0.03839721, 0.0283025 , 0.0159313 , ..., 0.01680337,
          0.01706766, 0.01516237],
         [0.03666214, 0.02661073, 0.0143979 , ..., 0.0205525 ,
          0.02097667, 0.01928506],
         [0.03457592, 0.02461651, 0.01266761, ..., 0.02414665,
          0.0247677 , 0.02331091],
         ...,
         [0.04115679, 0.04457412, 0.04827222, ..., 0.08595754,
          0.09237922, 0.09600829],
         [0.03995352, 0.04322341, 0.04666312, ..., 0.08578888,
          0.0919294 , 0.09534991],
         [0.0388893 , 0.04211677, 0.04536614, ..., 0.08561609,
          0.09137321, 0.09452485]]]], dtype=float32), array([[[[ 0.014237  ,  0.01757955,  0.02262362, ..., -0.12181864,
          -0.12416498, -0.12600493],
         [ 0.01824914,  0.02124377,  0.02605737, ..., -0.12328158,
          -0.1244223 , -0.1250075 ],
         [ 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f450abf8>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[-0.03306347, -0.03214611, -0.03139354, ...,  0.01784574,
           0.01754154,  0.01745088],
         [-0.0333252 , -0.03225467, -0.03126615, ...,  0.01674551,
           0.01646287,  0.01638907],
         [-0.0336009 , -0.03245724, -0.03133103, ...,  0.01570405,
           0.01543344,  0.0153511 ],
         ...,
         [-0.06531326, -0.0600263 , -0.05762076, ...,  0.01764578,
           0.01787042,  0.01745136],
         [-0.0773126 , -0.07542571, -0.07344631, ..., -0.00287038,
          -0.00266652, -0.00249286],
         [ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ]]]], dtype=float32), array([[[[ 0.01760195,  0.0179393 ,  0.01829431, ...,  0.        ,
           0.        ,  0.        ],
         [ 0.0165271 ,  0.01678899,  0.01698656, ...,  0.        ,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f42181e0>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[ 0.04746322,  0.04994434,  0.05309478, ...,  0.1511061 ,
           0.15716296,  0.1624527 ],
         [ 0.02781123,  0.03005574,  0.03245838, ...,  0.16980872,
           0.17414203,  0.17638513],
         [ 0.00806199,  0.00976358,  0.01197887, ...,  0.17964269,
           0.17841958,  0.17382504],
         ...,
         [ 0.03252233,  0.03889779,  0.04416591, ..., -0.09937722,
          -0.10423915, -0.10807212],
         [ 0.02181441,  0.02871248,  0.03558777, ..., -0.09801143,
          -0.10296609, -0.10645083],
         [ 0.01037902,  0.01755435,  0.02514467, ..., -0.09703229,
          -0.10185899, -0.10505796]]]], dtype=float32), array([[[[ 0.16621631,  0.1678346 ,  0.16700348, ..., -0.06723834,
          -0.06803612, -0.06926072],
         [ 0.1762126 ,  0.17361894,  0.16901481, ..., -0.06721037,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f456c6a8>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[ 0.04188155,  0.03877816,  0.03580325, ..., -0.02656269,
          -0.02160742, -0.02226952],
         [ 0.04172055,  0.04080819,  0.0397508 , ..., -0.03958907,
          -0.02736461, -0.02186661],
         [ 0.03497795,  0.03608856,  0.03701621, ..., -0.05801577,
          -0.03953878, -0.02656478],
         ...,
         [ 0.1267772 ,  0.1392645 ,  0.15100162, ..., -0.01463656,
          -0.01548554, -0.01596584],
         [ 0.12014252,  0.13111886,  0.14191501, ..., -0.00985131,
          -0.01136314, -0.01264343],
         [ 0.11402144,  0.12352359,  0.13308862, ..., -0.00551937,
          -0.00817579, -0.01069563]]]], dtype=float32), array([[[[-0.02726281, -0.03476148, -0.04297818, ...,  0.06046211,
           0.06771028,  0.0770578 ],
         [-0.02279594, -0.02847239, -0.03653457, ...,  0.06312636,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f4240620>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[-0.07971492, -0.08182734, -0.08364216, ..., -0.01776169,
          -0.01685225, -0.01586285],
         [-0.06877055, -0.07080731, -0.07255644, ..., -0.01376458,
          -0.01333362, -0.01280798],
         [-0.05833852, -0.06029807, -0.06197616, ..., -0.01023749,
          -0.01024196, -0.01016595],
         ...,
         [ 0.01373833,  0.01521454,  0.0160662 , ...,  0.08364252,
           0.07735889,  0.07049627],
         [ 0.01134212,  0.01238996,  0.0125385 , ...,  0.08686621,
           0.08065103,  0.07384927],
         [ 0.00856394,  0.0090237 ,  0.0084702 , ...,  0.08874892,
           0.08265608,  0.0759779 ]]]], dtype=float32), array([[[[-0.01523322, -0.015122  , -0.01546953, ...,  0.15091442,
           0.15376058,  0.15739891],
         [-0.01261226, -0.01293456, -0.01365903, ...,  0.16803378,
           0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f4edf378>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[-0.12112443, -0.10200721, -0.0833212 , ...,  0.04172228,
           0.03870749,  0.03604547],
         [-0.11923281, -0.10097078, -0.08237605, ...,  0.05147188,
           0.04912098,  0.04691814],
         [-0.11707065, -0.09948191, -0.08102971, ...,  0.05705279,
           0.05604877,  0.05508587],
         ...,
         [ 0.13171783,  0.12600979,  0.1183503 , ...,  0.02136075,
           0.01030782, -0.00270924],
         [ 0.12319804,  0.11861791,  0.11191603, ...,  0.02122964,
           0.01281748,  0.00056203],
         [ 0.11344557,  0.11017131,  0.10459951, ...,  0.01992693,
           0.01409513,  0.00290143]]]], dtype=float32), array([[[[ 0.03376393,  0.03186138,  0.03031309, ..., -0.01745894,
          -0.01074119, -0.00561454],
         [ 0.04492561,  0.04319042,  0.04171469, ..., -0.01653538,
          -0.
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b32f44e41e0>, (<function concrete at 0x2b325c96ea60>, [[[[array([[[[0.11790901, 0.11852564, 0.11948507, ..., 0.03190468,
          0.03043301, 0.0287886 ],
         [0.11904983, 0.11989289, 0.12100169, ..., 0.03225423,
          0.03083958, 0.02926585],
         [0.11990148, 0.12090042, 0.12211507, ..., 0.03264891,
          0.03128931, 0.02978941],
         ...,
         [0.07712747, 0.07802214, 0.07879199, ..., 0.04361812,
          0.04394455, 0.04462688],
         [0.07442316, 0.07533417, 0.07607353, ..., 0.04277806,
          0.04312806, 0.04384983],
         [0.0717777 , 0.0727186 , 0.07347642, ..., 0.04164363,
          0.04205994, 0.04287032]]]], dtype=float32), array([[[[ 0.02668881,  0.02393094,  0.0205733 , ...,  0.21257266,
           0.21132933,  0.20938967],
         [ 0.02725928,  0.02462862,  0.02141759, ...,  0.21596761,
           0.21439055,  0.21218745],
         [ 0
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.132:33214 remote=tcp://172.30.100.1:40264>
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.1:40264
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.132:33180 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.132:33288 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.132:33346 remote=tcp://172.30.100.1:40264>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.132:33338 remote=tcp://172.30.100.1:40264>
distributed.worker - INFO - Timed out when connecting to scheduler
distributed.worker - INFO - Stopping worker at tcp://172.30.8.132:39355
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.132:38915'
distributed.dask_worker - INFO - End worker
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-2, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-22, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-18, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-26, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-1, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-10, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-6, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-14, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-21, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-17, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-5, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-9, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-13, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-20, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-24, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-16, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-8, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-12, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-4, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-19, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-3, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-23, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-28, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-7, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-11, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-27, started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-15, started daemon)>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
