/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:42180'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:39378'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:38104'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:40814'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:36372'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:32890'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:41081'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:40661'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:36256'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:40305'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:43503'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:37210'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:45938'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:34446'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:37698'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:46167'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:44644'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:34219'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:36961'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:42444'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:35672'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:35374'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:33873'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:40121'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:41014'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:33978'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:46373'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.99:45918'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:34528
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:42897
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:34528
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:42897
distributed.worker - INFO -              nanny at:          172.30.8.99:46167
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:46781
distributed.worker - INFO -              nanny at:          172.30.8.99:34446
distributed.worker - INFO -              bokeh at:          172.30.8.99:42853
distributed.worker - INFO -              bokeh at:          172.30.8.99:40105
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:46781
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -              nanny at:          172.30.8.99:42180
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:          172.30.8.99:43024
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-quhdo070
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-i938wi8x
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ijs1h6yo
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:44879
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:44879
distributed.worker - INFO -              nanny at:          172.30.8.99:32890
distributed.worker - INFO -              bokeh at:          172.30.8.99:39009
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-jwx5owq1
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:35583
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:35583
distributed.worker - INFO -              nanny at:          172.30.8.99:35672
distributed.worker - INFO -              bokeh at:          172.30.8.99:35713
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-dq3d9kga
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:39201
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:39201
distributed.worker - INFO -              nanny at:          172.30.8.99:42444
distributed.worker - INFO -              bokeh at:          172.30.8.99:36415
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:42134
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:42134
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              nanny at:          172.30.8.99:45938
distributed.worker - INFO -              bokeh at:          172.30.8.99:33152
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-85jr6o4s
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-taamnmds
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:42515
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:42515
distributed.worker - INFO -              nanny at:          172.30.8.99:33873
distributed.worker - INFO -              bokeh at:          172.30.8.99:42618
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-qce73thb
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:40201
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:40201
distributed.worker - INFO -              nanny at:          172.30.8.99:33978
distributed.worker - INFO -              bokeh at:          172.30.8.99:39757
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.core - INFO - Starting established connection
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-wl9i0k70
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:46629
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:46629
distributed.worker - INFO -              nanny at:          172.30.8.99:46373
distributed.worker - INFO -              bokeh at:          172.30.8.99:39478
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-hzdza68h
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:46075
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:46075
distributed.worker - INFO -              nanny at:          172.30.8.99:37698
distributed.worker - INFO -              bokeh at:          172.30.8.99:36626
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-59lgz5hb
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:36356
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:36356
distributed.worker - INFO -              nanny at:          172.30.8.99:41014
distributed.worker - INFO -              bokeh at:          172.30.8.99:39676
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:35005
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:35005
distributed.worker - INFO -              nanny at:          172.30.8.99:37210
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              bokeh at:          172.30.8.99:42359
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-fpyup0uv
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-9hikiiz4
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:38434
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:38434
distributed.worker - INFO -              nanny at:          172.30.8.99:41081
distributed.worker - INFO -              bokeh at:          172.30.8.99:35138
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-z8evl6on
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:38775
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:38775
distributed.worker - INFO -              nanny at:          172.30.8.99:40814
distributed.worker - INFO -              bokeh at:          172.30.8.99:43457
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-vijn1_r7
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:39839
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:39839
distributed.worker - INFO -              nanny at:          172.30.8.99:45918
distributed.worker - INFO -              bokeh at:          172.30.8.99:45869
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ec40683q
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:44748
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:44748
distributed.worker - INFO -              nanny at:          172.30.8.99:40661
distributed.worker - INFO -              bokeh at:          172.30.8.99:34251
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1rnc_twg
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:38161
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:38161
distributed.worker - INFO -              nanny at:          172.30.8.99:36372
distributed.worker - INFO -              bokeh at:          172.30.8.99:46765
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-v31vafbr
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:45582
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:45582
distributed.worker - INFO -              nanny at:          172.30.8.99:36256
distributed.worker - INFO -              bokeh at:          172.30.8.99:35967
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-m_hdgfno
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:33738
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:33738
distributed.worker - INFO -              nanny at:          172.30.8.99:35374
distributed.worker - INFO -              bokeh at:          172.30.8.99:40643
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-hgt0ub4j
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:44005
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:44005
distributed.worker - INFO -              nanny at:          172.30.8.99:39378
distributed.worker - INFO -              bokeh at:          172.30.8.99:35169
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:39066
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:39066
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -              nanny at:          172.30.8.99:38104
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kipsnttd
distributed.worker - INFO -              bokeh at:          172.30.8.99:41004
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-cccd27jx
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:40832
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:40832
distributed.worker - INFO -              nanny at:          172.30.8.99:44644
distributed.worker - INFO -              bokeh at:          172.30.8.99:36364
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-3zqh6d4c
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:36146
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:36146
distributed.worker - INFO -              nanny at:          172.30.8.99:36961
distributed.worker - INFO -              bokeh at:          172.30.8.99:38678
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:44693
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:44693
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-d9f8ns3w
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:          172.30.8.99:40305
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:46464
distributed.worker - INFO -              bokeh at:          172.30.8.99:39593
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:46464
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:          172.30.8.99:43503
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -              bokeh at:          172.30.8.99:38007
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-xb_exk02
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ifb21n63
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:41833
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:41833
distributed.worker - INFO -              nanny at:          172.30.8.99:40121
distributed.worker - INFO -              bokeh at:          172.30.8.99:34149
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-yp2g3_li
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.99:42055
distributed.worker - INFO -          Listening to:    tcp://172.30.8.99:42055
distributed.worker - INFO -              nanny at:          172.30.8.99:34219
distributed.worker - INFO -              bokeh at:          172.30.8.99:45442
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-n116shtp
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58790 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58794 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58798 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58800 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58802 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58796 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58792 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58806 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58804 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58808 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43288 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43862 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43694 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43860 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43412 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43670 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43280 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43396 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43362 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43846 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43374 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43370 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43692 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43856 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43414 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43422 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43674 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43390 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43848 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43676 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43394 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43240 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43406 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43658 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43824 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43666 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43944 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43420 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43978 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43704 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43690 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43858 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43410 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43074 remote=tcp://172.30.100.2:45385>
distributed.utils_perf - INFO - full garbage collection released 14.71 MB from 224 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43684 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43236 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44472 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43578 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44530 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45020 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44660 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43764 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43784 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44020 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44468 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45054 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58786 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58788 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43238 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43798 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43408 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43744 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44474 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45022 remote=tcp://172.30.100.2:45385>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2adaac9e0208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44950 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44652 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45266 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44846 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45268 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44408 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45052 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44944 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45264 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43078 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44476 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43580 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44138 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43782 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58782 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58780 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:58784 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43780 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43582 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44946 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44140 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43778 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44480 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43808 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44952 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45406 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45062 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44254 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43788 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44282 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45176 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44458 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44566 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44622 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45358 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45378 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44682 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45444 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43398 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43786 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44286 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45178 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44450 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44570 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44618 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45362 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44680 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45434 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45522 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44868 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43980 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44034 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45412 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45065 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45100 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44314 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44372 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44428 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44482 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44540 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44596 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45334 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44706 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44746 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44790 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44902 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44956 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45012 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45466 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43546 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44664 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45342 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44216 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45424 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45166 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44384 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44440 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45278 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44608 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44712 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44802 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44858 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45112 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45222 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45474 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44290 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45184 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44452 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44568 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44628 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45354 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45376 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44678 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45443 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45528 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44878 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44926 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44988 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45038 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45078 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45122 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45296 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:43756 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44844 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44036 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45410 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45064 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45098 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44316 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44370 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44426 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44484 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45538 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44538 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44594 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45382 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44704 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44788 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44900 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44958 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45014 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45468 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44422 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45260 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44478 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44534 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44590 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45322 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45328 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44646 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44702 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45462 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44786 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44840 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44896 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45008 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45096 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45150 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45408 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45464 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45262 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44536 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44592 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:45380 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44714 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44842 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.99:44898 remote=tcp://172.30.100.2:45385>
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:39066
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:39839
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:41833
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:34528
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:35583
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:42515
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:45582
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:39201
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:44879
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:44748
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:38161
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:38775
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:40201
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:46464
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:38104'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:40121'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:46167'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:45918'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:44693
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:46075
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:36146
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:42134
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:35672'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:42897
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:38434
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:46629
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:36256'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:32890'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:42055
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:33873'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:42444'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:36372'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:40832
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:40661'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:46781
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:40814'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:33978'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:43503'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:40305'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:37698'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:45938'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:35005
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:33738
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:41081'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:46373'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:34446'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:34219'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:44644'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:42180'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:37210'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:35374'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:36356
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:36961'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:41014'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.99:44005
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.99:39378'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
