/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:37614'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:43104'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:36650'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:42454'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:41208'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:45585'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:33136'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:43789'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:35891'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:38919'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:32885'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:40866'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:32827'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:34902'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:41550'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:44782'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:42080'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:32969'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:41616'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:46046'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:42927'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:33796'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:39440'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:46692'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:46874'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:33054'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:44894'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.62:41689'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:42500
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:32855
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:42185
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:36335
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:32855
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:42500
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:37138
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:42185
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:36335
distributed.worker - INFO -              nanny at:          172.30.8.62:32969
distributed.worker - INFO -              nanny at:          172.30.8.62:41208
distributed.worker - INFO -              bokeh at:          172.30.8.62:34234
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:46040
distributed.worker - INFO -              nanny at:          172.30.8.62:38919
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:37138
distributed.worker - INFO -              bokeh at:          172.30.8.62:33424
distributed.worker - INFO -              bokeh at:          172.30.8.62:35723
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:46040
distributed.worker - INFO -              nanny at:          172.30.8.62:32885
distributed.worker - INFO -              nanny at:          172.30.8.62:36650
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -              nanny at:          172.30.8.62:41689
distributed.worker - INFO -              bokeh at:          172.30.8.62:38407
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -              bokeh at:          172.30.8.62:42261
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:          172.30.8.62:38946
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-2coylvmg
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_uvxvih1
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-5n_kqn85
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-i07h3e2u
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-t5m_lr03
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-mu05br9c
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:44467
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:44467
distributed.worker - INFO -              nanny at:          172.30.8.62:32827
distributed.worker - INFO -              bokeh at:          172.30.8.62:40390
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-890qz_j6
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:41830
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:41830
distributed.worker - INFO -              nanny at:          172.30.8.62:39440
distributed.worker - INFO -              bokeh at:          172.30.8.62:46164
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-woci3vut
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:45370
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:45370
distributed.worker - INFO -              nanny at:          172.30.8.62:43789
distributed.worker - INFO -              bokeh at:          172.30.8.62:41795
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-wltigqjc
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:38613
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:38613
distributed.worker - INFO -              nanny at:          172.30.8.62:42454
distributed.worker - INFO -              bokeh at:          172.30.8.62:38892
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-9vcusfqk
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:44753
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:44753
distributed.worker - INFO -              nanny at:          172.30.8.62:41616
distributed.worker - INFO -              bokeh at:          172.30.8.62:34613
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-tl8ocq8s
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:35474
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:35474
distributed.worker - INFO -              nanny at:          172.30.8.62:46874
distributed.worker - INFO -              bokeh at:          172.30.8.62:43727
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ceoldhhp
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:43255
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:43255
distributed.worker - INFO -              nanny at:          172.30.8.62:46046
distributed.worker - INFO -              bokeh at:          172.30.8.62:43678
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:37380
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-u1bqpa41
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:37380
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:          172.30.8.62:35891
distributed.worker - INFO -              bokeh at:          172.30.8.62:41512
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-s2r2wptd
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:36369
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:36369
distributed.worker - INFO -              nanny at:          172.30.8.62:44894
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:35355
distributed.worker - INFO -              bokeh at:          172.30.8.62:34654
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:35355
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -              nanny at:          172.30.8.62:34902
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:          172.30.8.62:33901
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_vhc6kze
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zsa_w2fl
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:46035
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:46035
distributed.worker - INFO -              nanny at:          172.30.8.62:44782
distributed.worker - INFO -              bokeh at:          172.30.8.62:42704
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:41074
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-5b0rkuyf
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:41074
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:          172.30.8.62:46692
distributed.worker - INFO -              bokeh at:          172.30.8.62:33911
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-i8tlt0pj
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:38736
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:43640
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:43640
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:38736
distributed.worker - INFO -              nanny at:          172.30.8.62:33054
distributed.worker - INFO -              nanny at:          172.30.8.62:33136
distributed.worker - INFO -              bokeh at:          172.30.8.62:38255
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -              bokeh at:          172.30.8.62:35889
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-g1kv1z2v
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-okpa__wb
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:37730
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:37730
distributed.worker - INFO -              nanny at:          172.30.8.62:43104
distributed.worker - INFO -              bokeh at:          172.30.8.62:43750
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-kz4afjqg
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:41732
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:41732
distributed.worker - INFO -              nanny at:          172.30.8.62:37614
distributed.worker - INFO -              bokeh at:          172.30.8.62:46514
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1wo53ui8
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:32952
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:37831
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:32952
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:37831
distributed.worker - INFO -              nanny at:          172.30.8.62:40866
distributed.worker - INFO -              bokeh at:          172.30.8.62:36607
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -              nanny at:          172.30.8.62:45585
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:          172.30.8.62:39084
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-pc7vq5b0
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-4efexvzl
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:44623
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:44623
distributed.worker - INFO -              nanny at:          172.30.8.62:42927
distributed.worker - INFO -              bokeh at:          172.30.8.62:42574
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:40463
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:40463
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -              nanny at:          172.30.8.62:33796
distributed.worker - INFO -              bokeh at:          172.30.8.62:35709
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-hp6resiv
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-jrfj3tqk
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:43816
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:43816
distributed.worker - INFO -              nanny at:          172.30.8.62:42080
distributed.worker - INFO -              bokeh at:          172.30.8.62:42279
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-3d5f4mfx
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.62:36559
distributed.worker - INFO -          Listening to:    tcp://172.30.8.62:36559
distributed.worker - INFO -              nanny at:          172.30.8.62:41550
distributed.worker - INFO -              bokeh at:          172.30.8.62:42680
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-n9frc5wz
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:44717
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45524 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45596 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45526 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45580 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45576 remote=tcp://172.30.100.2:44717>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b3a6cd6d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:44717' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45510 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45522 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45578 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45396 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45448 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45502 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45610 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45972 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45592 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45680 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45380 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45432 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45486 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45540 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45404 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45506 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45560 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45612 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45662 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45452 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45974 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45418 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45504 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45558 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45614 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45664 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45694 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45450 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45976 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45368 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45422 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45476 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:46038 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45371 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45426 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45480 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45372 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45428 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45478 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:46041 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45412 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45692 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45528 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45366 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:46036 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45416 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45566 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45622 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45514 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45984 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45420 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45410 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45564 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45616 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45456 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45508 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45978 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45376 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45424 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45482 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45574 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45408 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45688 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45384 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45436 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45382 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45434 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45542 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45364 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45414 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45690 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45394 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45446 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45500 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45608 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45970 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45392 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45442 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45390 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45444 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45400 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45572 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45626 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45518 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45988 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45568 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45406 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45620 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45512 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45982 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45440 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45386 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45438 remote=tcp://172.30.100.2:44717>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45594 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45378 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45430 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45484 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45538 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45562 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45618 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45668 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45398 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45454 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45980 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45402 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45570 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45674 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45516 remote=tcp://172.30.100.2:44717>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.62:45986 remote=tcp://172.30.100.2:44717>
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:44717
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:42500
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:43640
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:41830
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:36335
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:35355
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:44467
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:41074
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:41208'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:40463
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:43255
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:36369
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:33054'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:38613
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:32855
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:37138
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:39440'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:46035
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:46040
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:37380
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:44623
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:32952
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:42185
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:35474
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:45370
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:32885'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:37730
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:44753
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:41732
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:34902'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:32827'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:37831
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:43816
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:38736
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:46692'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:44782'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:33796'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:46046'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:42454'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:41689'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:36650'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:35891'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:42927'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:45585'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:44894'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:46874'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:33136'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:38919'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:32969'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.62:36559
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:43104'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:43789'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:41616'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:37614'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:40866'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:42080'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.62:41550'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
