/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:38527'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:40098'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:45680'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:33363'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:41452'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:39933'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:40591'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:46298'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:34564'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:41951'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:33325'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:37233'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:40868'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:45914'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:41966'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:44773'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:39295'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:33157'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:34237'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:38990'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:41321'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:40452'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:37027'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:41873'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:34056'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:46624'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:46803'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.6.153:40575'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:42363
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:42363
distributed.worker - INFO -              nanny at:         172.30.6.153:44773
distributed.worker - INFO -              bokeh at:         172.30.6.153:34531
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:40390
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:40390
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-7uunrjto
distributed.worker - INFO -              nanny at:         172.30.6.153:45914
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:         172.30.6.153:35441
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-5lsymro6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:39510
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:39510
distributed.worker - INFO -              nanny at:         172.30.6.153:34564
distributed.worker - INFO -              bokeh at:         172.30.6.153:36732
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-aeesou3q
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:36800
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:36800
distributed.worker - INFO -              nanny at:         172.30.6.153:46624
distributed.worker - INFO -              bokeh at:         172.30.6.153:35745
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-o_jgfq19
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:43491
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:43491
distributed.worker - INFO -              nanny at:         172.30.6.153:33325
distributed.worker - INFO -              bokeh at:         172.30.6.153:45423
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-hwqn0_8n
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:40974
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:40974
distributed.worker - INFO -              nanny at:         172.30.6.153:41873
distributed.worker - INFO -              bokeh at:         172.30.6.153:43181
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-9t6ux7d5
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:44922
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:44922
distributed.worker - INFO -              nanny at:         172.30.6.153:37233
distributed.worker - INFO -              bokeh at:         172.30.6.153:43251
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-a4x0hcw8
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:43368
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:43368
distributed.worker - INFO -              nanny at:         172.30.6.153:46803
distributed.worker - INFO -              bokeh at:         172.30.6.153:44687
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-p49o04c2
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:32918
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:32918
distributed.worker - INFO -              nanny at:         172.30.6.153:40868
distributed.worker - INFO -              bokeh at:         172.30.6.153:41408
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-j82cqrb3
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:35582
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:35582
distributed.worker - INFO -              nanny at:         172.30.6.153:38527
distributed.worker - INFO -              bokeh at:         172.30.6.153:38194
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1crva3b1
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:46513
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:46513
distributed.worker - INFO -              nanny at:         172.30.6.153:33363
distributed.worker - INFO -              bokeh at:         172.30.6.153:45518
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-7e8j8rpv
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:41700
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:41700
distributed.worker - INFO -              nanny at:         172.30.6.153:40575
distributed.worker - INFO -              bokeh at:         172.30.6.153:37285
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-aq0r_yll
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:34989
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:34989
distributed.worker - INFO -              nanny at:         172.30.6.153:39933
distributed.worker - INFO -              bokeh at:         172.30.6.153:42775
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-432_dsir
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:36523
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:36523
distributed.worker - INFO -              nanny at:         172.30.6.153:45680
distributed.worker - INFO -              bokeh at:         172.30.6.153:40693
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-s0q65fif
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:42238
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:42238
distributed.worker - INFO -              nanny at:         172.30.6.153:41951
distributed.worker - INFO -              bokeh at:         172.30.6.153:45158
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-p8gmu6oi
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:35989
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:35989
distributed.worker - INFO -              nanny at:         172.30.6.153:41452
distributed.worker - INFO -              bokeh at:         172.30.6.153:36987
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-21ssqwn2
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:43646
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:43646
distributed.worker - INFO -              nanny at:         172.30.6.153:34056
distributed.worker - INFO -              bokeh at:         172.30.6.153:33097
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-eubmws20
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:41117
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:41117
distributed.worker - INFO -              nanny at:         172.30.6.153:34237
distributed.worker - INFO -              bokeh at:         172.30.6.153:45391
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-l7d4icjg
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:45010
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:45010
distributed.worker - INFO -              nanny at:         172.30.6.153:40098
distributed.worker - INFO -              bokeh at:         172.30.6.153:45074
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1lgj615q
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:36735
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:36735
distributed.worker - INFO -              nanny at:         172.30.6.153:40452
distributed.worker - INFO -              bokeh at:         172.30.6.153:34496
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-eyh_kyju
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:46882
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:46882
distributed.worker - INFO -              nanny at:         172.30.6.153:37027
distributed.worker - INFO -              bokeh at:         172.30.6.153:44838
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-wny11je_
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:46711
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:46711
distributed.worker - INFO -              nanny at:         172.30.6.153:40591
distributed.worker - INFO -              bokeh at:         172.30.6.153:45606
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-00hxebjt
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:34597
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:34597
distributed.worker - INFO -              nanny at:         172.30.6.153:38990
distributed.worker - INFO -              bokeh at:         172.30.6.153:44653
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-yz6cynl0
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:46560
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:46560
distributed.worker - INFO -              nanny at:         172.30.6.153:33157
distributed.worker - INFO -              bokeh at:         172.30.6.153:45942
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-xo4h58hh
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:46551
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:46551
distributed.worker - INFO -              nanny at:         172.30.6.153:41966
distributed.worker - INFO -              bokeh at:         172.30.6.153:37536
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-5xfsus__
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:40045
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:40045
distributed.worker - INFO -              nanny at:         172.30.6.153:46298
distributed.worker - INFO -              bokeh at:         172.30.6.153:35080
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0qrtbx20
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:40132
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:40132
distributed.worker - INFO -              nanny at:         172.30.6.153:41321
distributed.worker - INFO -              bokeh at:         172.30.6.153:40470
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-fust7qto
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.6.153:37953
distributed.worker - INFO -          Listening to:   tcp://172.30.6.153:37953
distributed.worker - INFO -              nanny at:         172.30.6.153:39295
distributed.worker - INFO -              bokeh at:         172.30.6.153:35592
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ccvq1ze7
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.utils_perf - INFO - full garbage collection released 501.58 MB from 145 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47120 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47394 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47392 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47388 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47390 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47504 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47500 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47502 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47128 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47582 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47182 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b1dc6d8d208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47764 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47872 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47888 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47892 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47514 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47758 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47912 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47354 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47380 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47366 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47772 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47802 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47456 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47840 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47494 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47550 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47708 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47406 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47038 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47886 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47384 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47752 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47782 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47854 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47904 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47556 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47590 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47636 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47714 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48146 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47920 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47362 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47452 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47836 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47622 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47706 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47122 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47760 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47798 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47826 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47482 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47650 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47538 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47674 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47864 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:46946 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47884 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47720 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47370 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47404 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47776 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47844 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47496 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47898 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47554 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47628 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48142 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47762 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47874 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47682 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47916 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47358 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47926 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47426 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47446 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47478 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47612 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47648 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47666 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47700 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48166 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47400 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47800 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47458 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47832 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47488 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47796 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47822 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47476 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47698 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48162 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47890 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47780 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47850 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47530 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47560 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47592 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47690 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47716 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47806 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48152 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48140 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47778 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47846 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47528 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47900 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47558 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47630 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47688 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47710 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47804 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48144 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:46944 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47040 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47882 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47368 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47774 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47842 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47498 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47552 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47626 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47178 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47766 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47686 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47918 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47382 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47398 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47450 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47830 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47484 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47618 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47660 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47910 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47734 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47740 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47396 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47418 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47794 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47440 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47820 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47544 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47644 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48160 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47788 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47894 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47908 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47566 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47598 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47638 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47718 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47808 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47512 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47352 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47814 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47536 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47672 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47866 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47532 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47810 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47860 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47130 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47736 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47432 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47454 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47492 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47652 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47838 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47176 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47684 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47360 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47428 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47448 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47828 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47486 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47546 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47704 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47322 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47678 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47812 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47856 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47534 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47570 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47862 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48156 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47408 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47036 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47756 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47786 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47852 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47902 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47564 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47594 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47634 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47694 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48150 remote=tcp://172.30.100.2:37747>
distributed.utils_perf - INFO - full garbage collection released 13.76 MB from 1786 reference cycles (threshold: 10.00 MB)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47328 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47270 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47792 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47438 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47442 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47818 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47542 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47642 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47654 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47676 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47870 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48158 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47386 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47858 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47596 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47728 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47410 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47754 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47784 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47848 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47906 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47562 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47588 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47632 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47692 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47712 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:48148 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47118 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47876 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47680 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47914 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47356 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47928 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47424 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47444 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47824 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47480 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47610 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47646 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47664 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47702 remote=tcp://172.30.100.2:37747>
distributed.utils_perf - INFO - full garbage collection released 244.99 MB from 553 reference cycles (threshold: 10.00 MB)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47790 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47816 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47474 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47540 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47868 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47922 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47770 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47834 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.6.153:47548 remote=tcp://172.30.100.2:37747>
distributed.utils_perf - INFO - full garbage collection released 32.89 MB from 169 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b1e4ebf2d90>, (<function concrete at 0x2b1dcf4959d8>, [[[array([[[1.3899051, 1.430457 , 1.4644042, ..., 0.       , 0.       ,
         0.       ],
        [1.3979092, 1.433836 , 1.4645885, ..., 0.       , 0.       ,
         0.       ],
        [1.4033625, 1.4362323, 1.4651557, ..., 0.       , 0.       ,
         0.       ],
        ...,
        [1.4303116, 1.4892259, 1.5455929, ..., 0.       , 0.       ,
         0.       ],
        [1.4162495, 1.4755234, 1.5327221, ..., 0.       , 0.       ,
         0.       ],
        [1.4046581, 1.4599624, 1.5156696, ..., 0.       , 0.       ,
         0.       ]]], dtype=float32), array([[[0.        , 0.        , 0.        , ..., 0.07380655,
         0.07209143, 0.07065552],
        [0.        , 0.        , 0.        , ..., 0.07734108,
         0.07521014, 0.07305183],
        [0.        , 0.        , 0.        , ..., 0.08114243,
         0.079072
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.utils_perf - INFO - full garbage collection released 22.92 MB from 6714 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:42363
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:37953
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:44773'
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:43646
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:46513
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:36800
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:40132
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:46551
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:39295'
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:42238
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:36735
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:40045
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:39510
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:46882
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:34056'
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:43491
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:45010
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:46711
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:32918
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:34597
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:41117
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:35582
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:41700
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:43368
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:34989
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:40974
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:46560
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:41321'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:33363'
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:35989
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:41966'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:41951'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:46298'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:34564'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:40452'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:37027'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:33325'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:38990'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:40868'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:40098'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:40591'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:34237'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:38527'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:40575'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:46803'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:39933'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:41873'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:33157'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:41452'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:46624'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:40390
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:45914'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:44922
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:37233'
distributed.worker - INFO - Stopping worker at tcp://172.30.6.153:36523
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.6.153:45680'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
