/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:36940'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:35934'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:41760'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:44194'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:40265'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:34106'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:44057'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:36753'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:44991'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:45002'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:39115'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:44190'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:38053'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:45055'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:36733'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:40410'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:43349'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:40473'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:40320'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:45595'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:43698'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:41446'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:37645'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:36408'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:35741'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:38210'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:44010'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.173:44949'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:43497
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:43497
distributed.worker - INFO -              nanny at:         172.30.8.173:44190
distributed.worker - INFO -              bokeh at:         172.30.8.173:42355
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-nk249xmz
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:42783
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:42783
distributed.worker - INFO -              nanny at:         172.30.8.173:44057
distributed.worker - INFO -              bokeh at:         172.30.8.173:32852
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-xea74h99
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:40462
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:40462
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:36968
distributed.worker - INFO -              nanny at:         172.30.8.173:39115
distributed.worker - INFO -              bokeh at:         172.30.8.173:43307
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:36968
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO -              nanny at:         172.30.8.173:35934
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:         172.30.8.173:46445
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-dc5_eflt
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-z9ubgjxa
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:43466
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:43466
distributed.worker - INFO -              nanny at:         172.30.8.173:40473
distributed.worker - INFO -              bokeh at:         172.30.8.173:42805
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zi9m8ytq
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:35541
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:35541
distributed.worker - INFO -              nanny at:         172.30.8.173:45055
distributed.worker - INFO -              bokeh at:         172.30.8.173:41549
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-fikadlho
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:45738
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:45738
distributed.worker - INFO -              nanny at:         172.30.8.173:36733
distributed.worker - INFO -              bokeh at:         172.30.8.173:44036
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-tz3h6dg9
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:41091
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:41091
distributed.worker - INFO -              nanny at:         172.30.8.173:45595
distributed.worker - INFO -              bokeh at:         172.30.8.173:39335
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-1gca3f0t
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:39673
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:39673
distributed.worker - INFO -              nanny at:         172.30.8.173:37645
distributed.worker - INFO -              bokeh at:         172.30.8.173:39641
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-aqowfb2g
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:37059
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:37059
distributed.worker - INFO -              nanny at:         172.30.8.173:38210
distributed.worker - INFO -              bokeh at:         172.30.8.173:39740
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ugy1pobo
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:42212
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:42212
distributed.worker - INFO -              nanny at:         172.30.8.173:36753
distributed.worker - INFO -              bokeh at:         172.30.8.173:33555
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-07pihbgf
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:36673
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:36673
distributed.worker - INFO -              nanny at:         172.30.8.173:43349
distributed.worker - INFO -              bokeh at:         172.30.8.173:39221
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-bk2s72j3
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:45424
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:45424
distributed.worker - INFO -              nanny at:         172.30.8.173:36940
distributed.worker - INFO -              bokeh at:         172.30.8.173:36633
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-fpbt5st4
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:33141
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:33141
distributed.worker - INFO -              nanny at:         172.30.8.173:44194
distributed.worker - INFO -              bokeh at:         172.30.8.173:37341
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-y60dfex3
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:44361
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:44361
distributed.worker - INFO -              nanny at:         172.30.8.173:40410
distributed.worker - INFO -              bokeh at:         172.30.8.173:42524
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-fegeopqa
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:38900
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:38900
distributed.worker - INFO -              nanny at:         172.30.8.173:45002
distributed.worker - INFO -              bokeh at:         172.30.8.173:44546
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zy2b71j8
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:36835
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:36835
distributed.worker - INFO -              nanny at:         172.30.8.173:34106
distributed.worker - INFO -              bokeh at:         172.30.8.173:41891
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0ddc5j8q
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:46737
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:46737
distributed.worker - INFO -              nanny at:         172.30.8.173:44949
distributed.worker - INFO -              bokeh at:         172.30.8.173:45690
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-rsq4jyta
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:40119
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:40119
distributed.worker - INFO -              nanny at:         172.30.8.173:36408
distributed.worker - INFO -              bokeh at:         172.30.8.173:43447
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ce5qxotz
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:39711
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:39711
distributed.worker - INFO -              nanny at:         172.30.8.173:35741
distributed.worker - INFO -              bokeh at:         172.30.8.173:33095
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-xmakz3t0
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:42185
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:42185
distributed.worker - INFO -              nanny at:         172.30.8.173:40265
distributed.worker - INFO -              bokeh at:         172.30.8.173:33349
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-21pjazqn
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:46101
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:46101
distributed.worker - INFO -              nanny at:         172.30.8.173:41760
distributed.worker - INFO -              bokeh at:         172.30.8.173:33619
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-as6tlx5l
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:39972
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:39972
distributed.worker - INFO -              nanny at:         172.30.8.173:40320
distributed.worker - INFO -              bokeh at:         172.30.8.173:33813
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-a45uamfg
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:41894
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:41894
distributed.worker - INFO -              nanny at:         172.30.8.173:43698
distributed.worker - INFO -              bokeh at:         172.30.8.173:39219
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-55e88cju
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:32942
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:32942
distributed.worker - INFO -              nanny at:         172.30.8.173:44991
distributed.worker - INFO -              bokeh at:         172.30.8.173:41403
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-mx_brw_x
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:45902
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:45902
distributed.worker - INFO -              nanny at:         172.30.8.173:41446
distributed.worker - INFO -              bokeh at:         172.30.8.173:35498
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-z730jg23
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:42501
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:42501
distributed.worker - INFO -              nanny at:         172.30.8.173:38053
distributed.worker - INFO -              bokeh at:         172.30.8.173:38351
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-t03elt_o
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:   tcp://172.30.8.173:41675
distributed.worker - INFO -          Listening to:   tcp://172.30.8.173:41675
distributed.worker - INFO -              nanny at:         172.30.8.173:44010
distributed.worker - INFO -              bokeh at:         172.30.8.173:46428
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-szx0ivfz
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:37747
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.utils_perf - INFO - full garbage collection released 501.59 MB from 169 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:35938 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:35940 remote=tcp://172.30.100.2:37747>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36018 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2b7d0d73c208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:37747' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36706 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36806 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36810 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:35944 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36800 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36326 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36362 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36414 remote=tcp://172.30.100.2:37747>
distributed.utils_perf - INFO - full garbage collection released 41.97 MB from 1578 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:35942 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36466 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36722 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36376 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36462 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36556 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36734 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36776 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36266 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36710 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36372 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36730 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36398 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36758 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36428 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36814 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36332 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36694 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36716 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36766 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36434 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36492 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36654 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37148 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36022 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36336 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36438 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36698 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36354 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36720 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36774 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36586 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36658 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36668 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36812 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36626 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36310 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36330 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36404 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36764 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36490 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37144 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36726 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36750 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36416 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36482 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36818 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36468 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36742 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36786 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36184 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36470 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36504 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36604 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36788 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36130 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36704 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36228 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36346 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36386 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36752 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36420 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36484 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36544 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36646 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37138 remote=tcp://172.30.100.2:37747>
distributed.utils_perf - INFO - full garbage collection released 50.37 MB from 1514 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36218 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36284 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36616 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36872 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36772 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36480 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36852 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36510 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36540 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36574 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36592 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36612 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36638 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36794 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37162 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:35936 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36357 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36558 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36318 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36340 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36464 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36500 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36662 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36740 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36780 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37154 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36134 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36302 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36754 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36582 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36220 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36282 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36614 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36868 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36770 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36474 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36854 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36508 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36538 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36572 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36594 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36610 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36640 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36798 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37166 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/array/numpy_compat.py:28: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36222 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36280 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36874 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36384 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36748 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36476 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36848 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36514 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36536 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36576 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36584 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36598 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36608 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36642 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36796 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37160 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36444 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36356 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36342 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36344 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36498 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36548 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36560 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36664 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36736 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36778 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37156 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36088 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36522 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36808 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36622 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36666 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36370 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36396 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36832 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36486 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36550 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36756 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37140 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36360 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36320 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36338 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36496 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36562 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36660 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36738 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36782 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37157 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36172 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36308 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36712 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36374 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36732 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36402 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36762 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36554 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36652 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37146 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36216 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36278 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36870 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36380 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36746 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36478 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36850 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36512 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36534 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36570 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36596 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36606 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36792 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37164 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36816 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36628 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36312 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36334 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36696 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36718 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36768 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36436 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36494 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36656 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37150 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36516 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36128 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36702 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36230 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36802 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36347 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36388 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36418 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36546 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36644 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36624 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36306 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36328 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36714 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36400 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36760 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36488 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36552 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36650 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37142 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36262 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36518 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36132 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36226 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36804 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36618 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36856 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36678 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36366 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36390 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36422 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36542 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:37136 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36520 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36136 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36620 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36858 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36680 remote=tcp://172.30.100.2:37747>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36268 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36186 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36724 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36744 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36472 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36506 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36790 remote=tcp://172.30.100.2:37747>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.173:36784 remote=tcp://172.30.100.2:37747>
distributed.utils_perf - INFO - full garbage collection released 16.25 MB from 420 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<built-in function getitem>, (<function concatenate3 at 0x2b7d93e24488>, (<function concrete at 0x2b7d15e449d8>, [[[array([[[-0.03025895, -0.03079063, -0.03153091, ..., -0.15541488,
         -0.14679748, -0.14424162],
        [-0.03707007, -0.03859565, -0.04026853, ..., -0.15965334,
         -0.15517917, -0.15404633],
        [-0.04611271, -0.04857237, -0.05085336, ..., -0.1663049 ,
         -0.1635606 , -0.1605812 ],
        ...,
        [-0.13293517, -0.13952827, -0.1458641 , ..., -0.11261732,
         -0.10704798, -0.10079249],
        [-0.11983956, -0.1259119 , -0.13365637, ..., -0.1022595 ,
         -0.09690836, -0.09100307],
        [-0.11290732, -0.11622471, -0.12228831, ..., -0.09132069,
         -0.08628951, -0.08084688]]], dtype=float32), array([[[-0.14414604, -0.14301118, -0.14063156, ...,  1.1749624 ,
          1.1569309 ,  1.1377481 ],
        [-0.1520988 , -0.14863904, -0.14523472, ...,  1.1789461 ,
          1.1614188 ,  1.142484
kwargs:    {}
Exception: TimeoutError('Timeout')

distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.worker - WARNING - Heartbeat to scheduler failed
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.utils_perf - INFO - full garbage collection released 47.26 MB from 6612 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.utils_perf - INFO - full garbage collection released 47.12 MB from 6657 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:42501
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:45424
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:40462
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:41894
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:38053'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:39115'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:43466
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:32942
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:43698'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:39711
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:36835
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:40473'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:44361
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:36673
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:45738
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:42212
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:38900
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:44991'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:37059
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:33141
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:41675
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:39972
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:35741'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:34106'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:40410'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:43349'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:43497
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:36733'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:42185
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:36753'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:41091
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:39673
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:45902
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:45002'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:35541
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:46101
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:38210'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:42783
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:44194'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:44010'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:40320'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:44190'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:40265'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:37645'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:45055'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:41446'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:41760'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:45595'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:44057'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:46737
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:44949'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:36968
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:35934'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:36940'
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:37747
distributed.worker - INFO - Stopping worker at tcp://172.30.8.173:40119
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.173:36408'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
