/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:38320'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:44419'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:36977'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:38297'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:35897'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:40087'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:43829'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:40468'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:43451'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:43015'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:38637'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:36995'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:44651'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:39931'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:36580'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:45751'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:35906'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:37830'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:35601'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:42724'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:38158'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:41902'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:42980'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:36829'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:33253'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:42028'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:44079'
distributed.nanny - INFO -         Start Nanny at: 'tcp://172.30.8.98:40914'
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:41751
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:41751
distributed.worker - INFO -              nanny at:          172.30.8.98:37830
distributed.worker - INFO -              bokeh at:          172.30.8.98:35713
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-gew37fhi
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:37200
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:37200
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:37993
distributed.worker - INFO -              nanny at:          172.30.8.98:36829
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:37993
distributed.worker - INFO -              bokeh at:          172.30.8.98:35223
distributed.worker - INFO -              nanny at:          172.30.8.98:40468
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -              bokeh at:          172.30.8.98:43813
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-9pdh9a6x
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-rf5_ba67
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:46410
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:46410
distributed.worker - INFO -              nanny at:          172.30.8.98:38158
distributed.worker - INFO -              bokeh at:          172.30.8.98:35916
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:41256
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:41256
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -              nanny at:          172.30.8.98:35906
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-8_kwre9q
distributed.worker - INFO -              bokeh at:          172.30.8.98:35117
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ju7z7yjp
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:33027
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:33027
distributed.worker - INFO -              nanny at:          172.30.8.98:42724
distributed.worker - INFO -              bokeh at:          172.30.8.98:46210
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zyojbv49
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:36714
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:36714
distributed.worker - INFO -              nanny at:          172.30.8.98:35897
distributed.worker - INFO -              bokeh at:          172.30.8.98:43947
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-yfqdn5qr
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:33875
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:33875
distributed.worker - INFO -              nanny at:          172.30.8.98:38297
distributed.worker - INFO -              bokeh at:          172.30.8.98:34851
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-s84k10kx
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:44737
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:44737
distributed.worker - INFO -              nanny at:          172.30.8.98:43829
distributed.worker - INFO -              bokeh at:          172.30.8.98:34625
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-usgbrdvy
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:34485
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:34485
distributed.worker - INFO -              nanny at:          172.30.8.98:42980
distributed.worker - INFO -              bokeh at:          172.30.8.98:44064
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-0se1089j
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:43183
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:43183
distributed.worker - INFO -              nanny at:          172.30.8.98:43451
distributed.worker - INFO -              bokeh at:          172.30.8.98:37644
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-dw2b1tcs
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:46434
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:46434
distributed.worker - INFO -              nanny at:          172.30.8.98:33253
distributed.worker - INFO -              bokeh at:          172.30.8.98:36426
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-5i6ikl9f
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:36501
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:36501
distributed.worker - INFO -              nanny at:          172.30.8.98:43015
distributed.worker - INFO -              bokeh at:          172.30.8.98:45164
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-5kitjkjo
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:34204
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:34204
distributed.worker - INFO -              nanny at:          172.30.8.98:45751
distributed.worker - INFO -              bokeh at:          172.30.8.98:36472
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:43219
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:43219
distributed.worker - INFO -              nanny at:          172.30.8.98:42028
distributed.worker - INFO -              bokeh at:          172.30.8.98:35893
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-v1re11l0
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-fk41ru3f
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:45548
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:45548
distributed.worker - INFO -              nanny at:          172.30.8.98:36580
distributed.worker - INFO -              bokeh at:          172.30.8.98:34638
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-2ty71erf
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:34121
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:34121
distributed.worker - INFO -              nanny at:          172.30.8.98:35601
distributed.worker - INFO -              bokeh at:          172.30.8.98:35149
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-fh9y1e9u
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:34582
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:34582
distributed.worker - INFO -              nanny at:          172.30.8.98:38320
distributed.worker - INFO -              bokeh at:          172.30.8.98:43367
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-qqz9myzl
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:46265
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:46265
distributed.worker - INFO -              nanny at:          172.30.8.98:40087
distributed.worker - INFO -              bokeh at:          172.30.8.98:46345
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-qdv_be3v
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:36561
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:36561
distributed.worker - INFO -              nanny at:          172.30.8.98:44079
distributed.worker - INFO -              bokeh at:          172.30.8.98:38352
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-_78xzsb7
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:33286
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:33286
distributed.worker - INFO -              nanny at:          172.30.8.98:41902
distributed.worker - INFO -              bokeh at:          172.30.8.98:37441
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-p_nb243h
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:41023
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:41023
distributed.worker - INFO -              nanny at:          172.30.8.98:38637
distributed.worker - INFO -              bokeh at:          172.30.8.98:33145
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-poz_cq6s
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:42996
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:42996
distributed.worker - INFO -              nanny at:          172.30.8.98:44651
distributed.worker - INFO -              bokeh at:          172.30.8.98:45924
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-f06o0e5o
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:35391
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:35391
distributed.worker - INFO -              nanny at:          172.30.8.98:44419
distributed.worker - INFO -              bokeh at:          172.30.8.98:35717
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:44901
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:44901
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:40882
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-o95mtmuj
distributed.worker - INFO -              nanny at:          172.30.8.98:39931
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:40882
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              bokeh at:          172.30.8.98:34083
distributed.worker - INFO -              nanny at:          172.30.8.98:40914
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO -              bokeh at:          172.30.8.98:33065
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-by81cm7l
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-ek6zirzv
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:36811
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:36811
distributed.worker - INFO -              nanny at:          172.30.8.98:36977
distributed.worker - INFO -              bokeh at:          172.30.8.98:46510
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-60notf25
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
distributed.worker - INFO -       Start worker at:    tcp://172.30.8.98:45160
distributed.worker - INFO -          Listening to:    tcp://172.30.8.98:45160
distributed.worker - INFO -              nanny at:          172.30.8.98:36995
distributed.worker - INFO -              bokeh at:          172.30.8.98:35453
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.29 GB
distributed.worker - INFO -       Local Directory: /scratch/cnt0024/hmg2840/albert7a/daskjobqueue/worker-zs2_yjh6
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO -         Registered to:   tcp://172.30.100.2:45385
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Starting established connection
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44748 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44752 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44744 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44750 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44746 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44758 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44760 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44754 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44756 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44762 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44766 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44764 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44776 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44778 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44774 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44780 remote=tcp://172.30.5.156:33675>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44768 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44770 remote=tcp://172.30.5.156:33675>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:44772 remote=tcp://172.30.5.156:33675>
distributed.utils_perf - INFO - full garbage collection released 39.99 MB from 1278 reference cycles (threshold: 10.00 MB)
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48192 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49368 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48920 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48952 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49348 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48948 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48214 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49756 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49748 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48702 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48950 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49610 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48730 remote=tcp://172.30.100.2:45385>
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x2ab90110a208>>, <Future finished exception=OSError("Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time")>)
Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 218, in connect
    quiet_exceptions=EnvironmentError,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
tornado.util.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 748, in heartbeat
    address=self.contact_address, now=time(), metrics=self.get_metrics()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 736, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/core.py", line 864, in connect
    connection_args=self.connection_args,
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 230, in connect
    _raise(error)
  File "/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/comm/core.py", line 207, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://172.30.100.2:45385' after 10 s: connect() didn't finish in time
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49792 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49750 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49754 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49752 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48698 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50220 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50356 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50040 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49226 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50144 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50200 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49394 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49506 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50138 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49332 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50192 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49384 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49500 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49552 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50332 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50390 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50470 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49818 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48708 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50128 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49326 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50182 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49380 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49494 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50272 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50312 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49606 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50382 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49706 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50466 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49812 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49924 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49972 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50034 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50074 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50240 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50446 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50130 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49324 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50188 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49378 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49488 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50270 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50314 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49602 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50380 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49666 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49704 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49814 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49926 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49976 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50032 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50076 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50243 remote=tcp://172.30.100.2:45385>
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50222 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49786 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50012 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50052 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49246 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50164 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49358 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49412 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50480 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49468 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49522 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50290 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49578 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49636 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50428 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49732 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49848 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49904 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49954 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50106 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50416 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49892 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50406 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50098 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49292 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50156 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50210 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49404 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50262 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49460 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49516 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49572 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50326 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50350 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49628 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49676 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49724 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49780 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49836 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49948 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50002 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50444 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50132 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49318 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50180 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49374 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49486 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50306 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49596 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50328 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50378 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49664 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49700 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49806 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49922 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49970 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50024 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50066 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50238 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49562 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50282 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50342 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49618 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50396 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49770 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50472 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49826 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49938 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49992 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50088 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50256 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:48194 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:47970 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49912 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49088 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50300 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49144 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50370 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50118 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49312 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50230 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49592 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49642 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49694 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49744 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:49800 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50022 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50062 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50174 remote=tcp://172.30.100.2:45385>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://172.30.8.98:50420 remote=tcp://172.30.100.2:45385>
distributed.utils_perf - INFO - full garbage collection released 27.21 MB from 4581 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/xarray/core/merge.py:16: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.client - ERROR - Failed to reconnect to scheduler after 3.00 seconds, closing client
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:43219
distributed.worker - INFO - Waiting to connect to:   tcp://172.30.100.2:45385
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:36811
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:43183
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:42028'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:41751
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:40882
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:36977'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:43451'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:36714
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:36501
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:34121
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:33286
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:37830'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:37993
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:40914'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:46434
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:33027
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:34485
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:35897'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:43015'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:46410
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:41902'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:41256
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:44901
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:35601'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:33875
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:44737
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:41023
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:42996
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:40468'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:36561
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:45548
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:37200
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:45160
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:42724'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:46265
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:35391
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:42980'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:33253'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:35906'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:38297'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:38158'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:39931'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:44079'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:43829'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:44651'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:38637'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:36580'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:34582
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:36829'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:44419'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:40087'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:36995'
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:38320'
distributed.worker - INFO - Stopping worker at tcp://172.30.8.98:34204
distributed.nanny - INFO - Closing Nanny at 'tcp://172.30.8.98:45751'
distributed.dask_worker - INFO - End worker
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/scratch/cnt0024/hmg2840/albert7a/anaconda3/lib/python3.7/site-packages/distributed/utils.py:136: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  RuntimeWarning,
